name: match
description: match flutter project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter_native_splash: ^2.3.3 # splash
  kakao_flutter_sdk: ^1.5.0 # 전체 추가
  kakao_flutter_sdk_user: ^1.5.0 # 카카오 로그인
  kakao_flutter_sdk_talk: ^1.5.0 # 카카오톡 메시지, 카카오톡 소셜(프로필 가져오기, 친구 목록 가져오기)
  kakao_flutter_sdk_story: ^1.5.0 # 카카오스토리
  kakao_flutter_sdk_share: ^1.6.0 # 카카오톡 공유
  kakao_flutter_sdk_navi: ^1.5.0 # 카카오내비
  kakao_flutter_sdk_friend: ^1.5.0 # 카카오톡 소셜(피커: 친구 선택하기)
  flutter_naver_login: ^1.8.0 # 네이버 로그인
  sign_in_with_apple: ^5.0.0 # 애플 로그인

  flutter:
    sdk: flutter

  webview_flutter: ^4.0.7

  intl: ^0.18.1 # Date Picker

  http: ^0.13.3
  retrofit: ^4.0.2

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.7.0
  flutter_svg: ^1.1.6
  logger: ^1.3.0
  fluttertoast: ^8.2.2
  dio: ^5.2.1
  freezed_annotation: ^2.2.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.14
  flutter_localization: ^0.1.14
  freezed: ^2.4.2
  carousel_slider: ^4.2.1
  json_annotation: ^4.8.1
  timeline_tile_nic: ^2.0.1
  timezone: ^0.9.2
  contained_tab_bar_view: ^0.8.0
  appsflyer_sdk: ^6.12.2
  firebase_dynamic_links: ^5.3.7
  firebase_core: ^2.17.0
  permission_handler: ^11.0.1
  image_gallery_saver: ^2.0.3
  uni_links: ^0.5.1
  get_storage: ^2.1.1

  syncfusion_flutter_datepicker: ^23.1.40
  firebase_in_app_messaging: ^0.7.4+1
  firebase_messaging: ^14.7.1
  device_info: ^2.0.3
  shimmer: ^3.0.0
  flutter_local_notifications: ^16.1.0

dev_dependencies:
  retrofit_generator: ^8.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_annotation: ^4.8.1
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - asset/image/
    - asset/image/icon/bottomNavi/
    - asset/image/icon/login/
    - asset/image/icon/card/
    - asset/image/icon/payment/
    - asset/image/icon/
    - asset/image/icon/project/
    - asset/image/icon/mypage/
    - asset/image/logo/
    - asset/image/onboarding/

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: asset/font/appleSD/AppleSDGothicNeoUL.ttf
          weight: 100
        - asset: asset/font/appleSD/AppleSDGothicNeoT.ttf
          weight: 200
        - asset: asset/font/appleSD/AppleSDGothicNeoSB.ttf
          weight: 300
        - asset: asset/font/appleSD/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: asset/font/appleSD/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: asset/font/appleSD/AppleSDGothicNeoL.ttf
          weight: 600
        - asset: asset/font/appleSD/AppleSDGothicNeoH.ttf
          weight: 700
        - asset: asset/font/appleSD/AppleSDGothicNeoEB.ttf
          weight: 800
        - asset: asset/font/appleSD/AppleSDGothicNeoB.ttf
          weight: 900

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
