name: match
description: match flutter project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  kakao_flutter_sdk: ^1.5.0 # 전체 추가
  kakao_flutter_sdk_user: ^1.5.0 # 카카오 로그인
  kakao_flutter_sdk_talk: ^1.5.0 # 카카오톡 메시지, 카카오톡 소셜(프로필 가져오기, 친구 목록 가져오기)
  kakao_flutter_sdk_story: ^1.5.0 # 카카오스토리
  kakao_flutter_sdk_share: ^1.5.0 # 카카오톡 공유
  kakao_flutter_sdk_navi: ^1.5.0 # 카카오내비
  kakao_flutter_sdk_friend: ^1.5.0 # 카카오톡 소셜(피커: 친구 선택하기)

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.7.0
  flutter_svg: ^1.1.6
  logger: ^1.3.0
  fluttertoast: ^8.2.2
  dio: ^5.2.1
  freezed_annotation: ^2.2.0
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.14
  flutter_localization: ^0.1.14
  freezed: ^2.4.2
  carousel_slider: ^4.2.1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - .env
    - asset/image/
    - asset/image/icon/bottomNavi/
    - asset/image/icon/login/
    - asset/image/icon/
    - asset/image/logo/

  fonts:
    - family: AppleSDGothicNeo
      fonts:
        - asset: asset/font/appleSD/AppleSDGothicNeoUL.ttf
          weight: 100
        - asset: asset/font/appleSD/AppleSDGothicNeoT.ttf
          weight: 200
        - asset: asset/font/appleSD/AppleSDGothicNeoSB.ttf
          weight: 300
        - asset: asset/font/appleSD/AppleSDGothicNeoR.ttf
          weight: 400
        - asset: asset/font/appleSD/AppleSDGothicNeoM.ttf
          weight: 500
        - asset: asset/font/appleSD/AppleSDGothicNeoL.ttf
          weight: 600
        - asset: asset/font/appleSD/AppleSDGothicNeoH.ttf
          weight: 700
        - asset: asset/font/appleSD/AppleSDGothicNeoEB.ttf
          weight: 800
        - asset: asset/font/appleSD/AppleSDGothicNeoB.ttf
          weight: 900

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
