const String RESULT = "result";
const String SUCCESS = "isSuccess";
const String MSG = "message";
const String CODE = "code";
const String LAST = "isLast";
const String TOTAL = "totalCnt";
const String CONTENTS = "contents";
const String NOTIFICATIONS = "notificationLists";
///* pagination 기본 호출 단위
const int PAGINATION_SIZE = 20;
const String TOKEN_HEADER = 'X-AUTH-TOKEN';
const String REFRESH_HEADER = 'X-REFRESH-TOKEN';