const String RESULT = "result";
const String SUCCESS = "isSuccess";
const String MSG = "message";
const String CODE = "code";
const String LAST = "isLast";
const String TOTAL = "totalCnt";
const String CONTENTS = "contents";
///* pagination 기본 호출 단위
const int PAGINATION_SIZE = 5;
